version: '3.8'

services:
  teen-budget-tracker:
    image: tigreroll/teen-budget-tracker:v1.0.12
    container_name: teen-budget-tracker
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - teen_budget_data:/app/data
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/teen-budget.db
      - NEXTAUTH_URL=http://localhost:3001
      - NEXTAUTH_SECRET=teen-budget-tracker-production-secret-2024
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://0.0.0.0:3001/api/auth/users"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.docker.compose.project=teen-budget-tracker"
      - "com.docker.compose.service=web"
      - "app.version=1.0.12"
      - "app.description=Teen Budget Tracker - Personal finance management"
      - "maintenance.backup.enable=true"
      - "maintenance.update.check=daily"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

volumes:
  teen_budget_data:
    driver: local
    labels:
      - "com.docker.compose.project=teen-budget-tracker"
      - "backup.enable=true"
      - "backup.frequency=daily"

networks:
  default:
    name: teen-budget-network
    labels:
      - "com.docker.compose.project=teen-budget-tracker"